package sep3.entity;

import jakarta.persistence.*;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

@Entity
public class Cow
{
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;
    @Column(unique = true) //making sure no duplicate cows are registered
    private String regNo;
    private LocalDate birthDate;
    private boolean isHealthy;
    // it will be quarantined until health is confirmed, so the default is false
    @ManyToOne
    @JoinColumn(name = "department_id")
    // This creates a foreign key 'department_id' in the cow table automatically.
    private Department department;

    @ManyToOne
    @JoinColumn(name = "registered_by")
    private User registeredBy;

  // Initializing the lists to avoid NullPointerExceptions
  @OneToMany(mappedBy = "cow", cascade = CascadeType.ALL)
  private List<TransferRecord> transferRecords = new ArrayList<>();

  @OneToMany(mappedBy = "cow", cascade = CascadeType.ALL)
  private List<Milk> milk = new ArrayList<>();

    protected Cow() {}

  //constructor for adding a new cow to a herd, no id because it's generated by DB'
  public Cow(String regNo, LocalDate birthDate, Department initialDepartment,
      User registeredBy)
  {
    this.regNo = regNo;
    this.birthDate = birthDate;
    this.isHealthy = false; //new cows are marked unhealthy by default
    this.department = initialDepartment; //TODO: make sure this is the quarantine department
    this.registeredBy = registeredBy;
  }

    public Cow(String regNo, LocalDate birthDate, boolean isHealthy, User registeredBy)
    {
        this.regNo = regNo;
        this.birthDate = birthDate;
        this.isHealthy = isHealthy;
        this.registeredBy = registeredBy;
    }


  //getters and setters

  public long getId()
  {
    return id;
  }

  public void setId(long id)
  {
    this.id = id;
  }

  public String getRegNo()
  {
    return regNo;
  }

  public void setRegNo(String regNo)
  {
    this.regNo = regNo;
  }

  public LocalDate getBirthDate()
  {
    return birthDate;
  }

  public void setBirthDate(LocalDate birthDate)
  {
    this.birthDate = birthDate;
  }

  public boolean isHealthy()
  {
    return isHealthy;
  }

  public void setHealthy(boolean healthy)
  {
    isHealthy = healthy;
  }

  public User getRegisteredBy()
  {
    return registeredBy;
  }
  
  public void setRegisteredBy(User registeredBy)
  {
    this.registeredBy = registeredBy;
  }

  public Department getDepartment()
  {
    return department;
  }

  public void setDepartment(Department department)
  {
    this.department = department;
  }
  //getters for jpa

  public List<TransferRecord> getTransferRecords()
  {
    return transferRecords;
  }


  public List<Milk> getMilk()
  {
    return milk;
  }

  //Helper Methods (Safe setters)
  public void addMilk(Milk milkEntry) {
      this.milk.add(milkEntry);
      milkEntry.setCow(this); // Maintains the relationship
  }

  public void removeMilk(Milk milkEntry) {
      this.milk.remove(milkEntry);
      milkEntry.setCow(null);
  }

  public void addTransferRecord(TransferRecord transferRecord)
  {
    transferRecords.add(transferRecord);
  }

  public void cancelTransferRecord(TransferRecord transferRecord)
  {
    transferRecords.remove(transferRecord);
  }

}
